// After obtaining the token
localStorage.setItem(
  "accessToken",
  "veyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhMzk5ZWIyOTRkZDhiNDBhNDg1NTk3NmM0ZjVlYjIyYSIsInN1YiI6IjY0Y2EzZjZmZGQ4M2ZhMDBmZjUxODEwNyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.CoTAs4nhvVWLzTXbtt-fYiJ_HfefqjkBe36Ee2hMzW8"
);
